spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/golden-house?serverTimezone=UTC

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file://${golden.upload.base-path}

logging:
  level:
    com.ideal.golden.mapper: debug

golden:
  prop-config:
    cors-origins:
      - http://127.0.0.1:5500
  upload:
    base-path: /Users/weidian/liuhaonan/case/upload/
    img-path: img/
    file-path: file/
    video-path: video/

